[versions]
agp = "9.0.1"
kotlin = "2.3.10"
compose = "1.10.1"
ksp = "2.3.3"
google-services = "4.4.4"
firebase-crashlytics = "3.0.6"
androidx-activity = "1.12.4"
androidx-lifecycle = "2.9.6"
androidx-datastore = "1.2.0"
kotlinx-collections = "0.4.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
kotlinx-serialization = "1.10.0"
tink-android = "1.20.0"
ktor = "3.4.0"
koin = "4.1.1"
koin-annotations = "2.3.1"
firebase = "34.9.0"
navigation = "2.9.2"
navigation-event = "1.0.1"
material-icons = "1.7.3"
m3 = "1.9.0"
m3-adaptive = "1.2.0"
landscapist = "2.9.5"

#UNIT TEST
mokkery = "3.2.0"
kotlinx-coroutines-test = "1.10.2"
app-cash-turbine = "1.2.1"

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }

#ANDROIDX + NAVIGATION
navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }
navigation-event = { module = "org.jetbrains.androidx.navigationevent:navigationevent-compose", version.ref = "navigation-event" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }

#noinspection UnusedVersionCatalogEntry
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

#LIFECYCLE
lifecycle-runtime = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

#KOTLINX
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-collections = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

#GOOGLE
google-tink-android = { module = "com.google.crypto.tink:tink-android", version.ref = "tink-android" }

#KOIN
#noinspection UnusedVersionCatalogEntry
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin-annotations" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-ksp-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koin-annotations" }
koin-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
koin-viewmodel-navigation = { group = "io.insert-koin", name = "koin-compose-viewmodel-navigation", version.ref = "koin" }

#KTOR
ktor-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
ktor-content = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

#FIREBASE
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
#noinspection UnusedVersionCatalogEntry
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }

#UNIT TEST
turbine = { module = "app.cash.turbine:turbine", version.ref = "app-cash-turbine" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }

#COMPOSE
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose"}
compose-material-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "material-icons"}
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose"}
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose"}
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose"}
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose"}
#noinspection UnusedVersionCatalogEntry
compose-uiTooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }

#MATERIAL3
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "m3"}
material3-adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "m3-adaptive" }
material3-adaptive-layout = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-layout", version.ref = "m3-adaptive" }
material3-adaptive-navigation = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "m3-adaptive" }

#OTHER
landscapist-image = { module = "com.github.skydoves:landscapist-image", version.ref = "landscapist" }
landscapist-placeholder = { module = "com.github.skydoves:landscapist-placeholder", version.ref = "landscapist" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
mokkery = { id = "dev.mokkery", version.ref = "mokkery"}
google-services = { id = "com.google.gms.google-services", version.ref = "google-services"}
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics"}

#CONVENTION
convention-android-application = { id = "base.android.application", version = "unspecified" }
convention-kmp-ksp = { id = "base.kmp.ksp", version = "unspecified" }
convention-kmp-compose = { id = "base.kmp.compose", version = "unspecified" }
convention-kmp-library = { id = "base.kmp.library", version = "unspecified" }
convention-kmp-feature = { id = "base.kmp.feature", version = "unspecified" }

[bundles]
datastore = ["androidx-datastore", "androidx-datastore-preferences"]
kotlinx = ["kotlinx-collections", "kotlinx-coroutines", "kotlinx-datetime", "kotlinx-serialization-json"]
ktor = ["ktor-auth", "ktor-content", "ktor-core", "ktor-logging", "ktor-serialization"]
koin-annotations = ["koin-annotations", "koin-core"]
lifecycle = ["lifecycle-runtime", "lifecycle-viewmodel"]
test = ["koin-test", "kotlin-test", "kotlinx-coroutines-test", "turbine"]
#noinspection UnusedVersionCatalogEntry
koin = ["koin-annotations", "koin-compose", "koin-viewmodel", "koin-viewmodel-navigation"]
#noinspection UnusedVersionCatalogEntry
compose = ["material3", "compose-foundation", "compose-material-icons", "compose-runtime", "compose-ui", "compose-ui-tooling-preview"]
#noinspection UnusedVersionCatalogEntry
material3-adaptive = ["material3-adaptive", "material3-adaptive-layout", "material3-adaptive-navigation"]
image-loader = ["landscapist-image", "landscapist-placeholder"]